---
- name: Power off all hosts
  hosts: all
  become: yes

  tasks:
    - name: Halt machines
      shell: sleep 5 && shutdown -h now
      async: 1
      poll: 0 
    
    - name: Check for silence
      wait_for_connection:
        delay: 5 
        timeout: 10
      register: wait_result
      failed_when: "'Failed to connect' not in wait_result.msg"

...

